name: urban-heat
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyter
  - rasterio
  - rioxarray
  - xarray
  - geopandas
  - rasterstats
  - pandas
  - netcdf4
  - numpy
  - matplotlib
  - seaborn
  - contextily
  - scipy
  - pip
  - pip:
    - pymannkendall